### PR TITLE
Share build scheme for Carthage

### PR DESCRIPTION
**Pull request by aceontech**
Shared the build scheme so Carthage can build. Cartfile example:

```
github "100mango/SwiftNotificationCenter" ~> 1.0
```

### CODE REVIEW

**Comment by aceontech** [comment]
Awesome!

**Comment by aceontech** [comment]
@100mango I think a Github release version increment will be necessary for Carthage to pick it up, e.g. `1.0.1`.

```sh
** Checking out SwiftNotificationCenter at "1.0.0"
*** xcodebuild output can be found in /var/folders/_7/69ggd6pj5ndd7yds_317tzrc0000gn/T/carthage-xcodebuild.pWBoX0.log
*** Skipped building SwiftNotificationCenter due to the error:
Dependency "SwiftNotificationCenter" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/100mango/SwiftNotificationCenter/issues/new
```

**Comment by 100mango** [comment]
@aceontech  I haven't work with Carthage. Please make sure the correct process and make it available.

**Comment by aceontech** [comment]
Hi @100mango,

Carthage relies on Xcode's build scheme being shared (which is done) and on proper Git tagging. The only thing you need to do to make this first Carthage build work, is put a new version tag on the master branch (e.g. 1.0.1). I can't add tags to pull requests so you'll need to do this.

Going forward, Carthage should just work.

Thanks!
-- Alex

**Comment by 100mango** [comment]
Thanks. @aceontech . I have created a new tag. Would you mind having a test and update the README with the Carthage install way? Thanks.

**Comment by aceontech** [comment]
Gladly. Will try to get to it later on.
Thanks again @100mango for the great little utility you wrote. I started
using it in one of my projects this week.

**Pull request merged**
