### PR TITLE
Update to Swift 3 Syntax

### PR DESCRIPTION
**Pull request by Moonisky**
Update the Framework & Demo

### CODE REVIEW

**Comment by aceontech** [comment]
I see that you've accommodated Swift 3's renaming of `NSNotificationCenter` to NotificationCenter 👍. Not sure about`NotifyCenter` as the new name though.. How does the rest see this?

**Comment by 100mango** [comment]
@aceontech  I have created a Swift3 branch, you are welcome to have a look. I am consider using the Broadcaster as the new name. But I am currently focusing on how to deal with the `Any` and `AnyObject` after Xcode8 beta6 came up. The swift core team decided making everything bridges to AnyObject. I have filed a bug about it. You can found the discussion [here](https://bugs.swift.org/browse/SR-2420). Welcome for any suggestion.

**Comment by gapl** [comment]
What is the progress with `Swift3` branch? I would love to use that in my project and I see it is currently behind master by 6 commits.

**Comment by 100mango** [comment]
@gapl The Swift3 branch had been merged to master branch already. Please have a check.

**Pull request closed without merging**
